stages:
  - test
  - build
  - publish
Test:
  image: python
  script: "make test"
Test Coverage:
  image: python
  script: "make cover"
  before_script:
    - "pip3 install coverage"
  coverage: '/TOTAL +\d+ +\d+ +(\d+)\%\s*$/'
Style Check:
  image: python
  script: "make style"
  before_script:
    - "pip3 install pycodestyle"
Build Package:
  stage: build
  image: python
  script: "make build"
  only: ['tags']
  artifacts:
    paths:
      - dist/
Publish Package:
  stage: publish
  image: python
#  script: "twine upload dist/* -u $TWINE_USERNAME -p $TWINE_PASSWORD"
  script:
    - echo $TWINE_USERNAME
  before_script:
    - "pip3 install twine"
  only: ['tags']
