include:
  template: SAST.gitlab-ci.yml

stages:
  - test
  - build
  - publish

Test:
  image: python
  script: "make test"

Test Coverage:
  image: python
  script: "make cover"
  before_script:
    - "pip3 install coverage"
  coverage: '/TOTAL +\d+ +\d+ +(\d+)\%\s*$/'

Style Check:
  image: python
  script: "make style"
  before_script:
    - "pip3 install pycodestyle"

Code Quality:
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env SOURCE_CODE="$PWD"
        --volume "$PWD":/code
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
  artifacts:
    reports:
      codequality: gl-code-quality-report.json

Build Package:
  stage: build
  image: python
  script: "make build"
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/
  artifacts:
    paths:
      - dist/

Publish Package:
  stage: publish
  image: python
  script:
    - echo "Attempting publishing to PyPI using $TWINE_USERNAME"
    - make publish
  before_script:
    - "pip3 install twine"
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/
