stages:
  - Test
  - Build
Test:
  image: python
  script: "make test"
Test Coverage:
  image: python
  script: "make cover"
  before_script:
    - "pip3 install coverage"
  coverage: '/TOTAL +\d+ +\d+ +(\d+)\%\s*$/'
Style Check:
  image: python
  script: "make style"
  before_script:
    - "pip3 install pycodestyle"
Build:
  stage: Build
  script: "make build"
  only: ['tags']
  artifacts:
    paths:
      - dist/
